In [1]:
import numpy as np
import pandas as pd
from tensorflow import keras
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [3]:
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()
train_scaled = train_input/255.0

In [5]:
# train data 일부를 검증(val)세트로 만들어주기
train_scaled,val_scaled,train_target,val_target = train_test_split(
    train_scaled,train_target,test_size=0.2,random_state=42
)

In [6]:
model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28)))
model.add(keras.layers.Dense(100,activation='relu',name='hidden')) # 'sigmoid'
model.add(keras.layers.Dropout(0.3))  # 30%를 제외시키는 규제적용
model.add(keras.layers.Dense(10,activation='softmax',name='output'))

In [9]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden (Dense)                  │ (None, 100)            │        78,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 238,532 (931.77 KB)

 Trainable params: 79,510 (310.59 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 159,022 (621.18 KB)

In [8]:
# model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# # epochs 돌때마다 loss,accuracy 값을 저장
# # train_scaled, val_scaled를 함께 훈련 시킴
# history = model.fit(train_scaled, train_target,epochs=20,
#                     validation_data=(val_scaled,val_target))

In [11]:
# 이전에 돌린 모델 훈련을 그대로 출력할 수 있게끔 저장 후 불러온 것(load_weights)
model.load_weights('model0529.weights.h5')      # 가중치만 저장한 것

In [12]:
model.predict(val_scaled)

375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


array([[1.2941920e-12, 2.3649467e-16, 2.0320100e-17, ..., 5.0162665e-12,
        1.0000000e+00, 2.1737765e-16],
       [8.9497769e-09, 2.1345645e-15, 7.3127913e-13, ..., 5.8989381e-16,
        1.0000000e+00, 1.2691394e-14],
       [7.1998223e-13, 2.9392371e-09, 9.1500819e-16, ..., 9.9932408e-01,
        5.1942175e-07, 4.8871379e-06],
       ...,
       [5.6356093e-06, 1.5325690e-13, 1.2444251e-10, ..., 7.0907419e-10,
        9.9999368e-01, 4.6118886e-09],
       [3.6092444e-12, 2.2800783e-18, 7.7952008e-16, ..., 1.0761009e-17,
        1.0000000e+00, 5.1860642e-19],
       [2.2476624e-01, 8.0571894e-08, 6.9606388e-03, ..., 3.8959868e-08,
        3.5197177e-06, 8.1525424e-05]], dtype=float32)

In [14]:
# val_scaled의 답
val_target

array([8, 8, 7, ..., 8, 8, 1], dtype=uint8)

In [16]:
# model_weights 를 읽어와서 데이터 처리
val_labels = np.argmax(model.predict(val_scaled),axis=-1) # axis: 세로=0, 가로=1, 맨끝=-1(??): 가로를 말하는 것과 동일
np.mean(val_labels == val_target) # 가장 높은 값중에, 정답과 일치한 것만 평균값 계산에 넣어달라는 의미

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


0.8845833333333334

In [17]:
val_labels

array([8, 8, 7, ..., 8, 8, 6], dtype=int64)

In [19]:
# 모델 전체를 저장한 것을 불러와 처리
model = keras.models.load_model('model_all.h5')

In [20]:
model.evaluate(val_scaled,val_target)

375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8853 - loss: 0.3265


[0.32791757583618164, 0.8845833539962769]