### python 복습

### Markdown 수식 작성
    - LaTex 태그로 작성 가능
$$ 
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6
    \end{pmatrix}
    + 
    \begin{pmatrix}
    5 & 5 & 5 \\
    5 & 5 & 5
    \end{pmatrix}
$$
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5 & 5 \\
    5 & 5 \\
    5 & 5
    \end{pmatrix}
$$ 

### Numpy
    - 데이터는 행렬로 표현(영상도 포함)
    - 선형대수\통계 연산을 위한 라이브러리

    Pandas : 데이터 분석에 가장 많이 활용
    Numpy : 알고리즘 활용에 numpy가 필수적 패키지

In [3]:
# 호출 
import numpy as np

### array broadcasting
    - 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
    - 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [8]:
ary = np.array(np.random.randint(10,100,10))    
ary

array([92, 12, 10, 98, 49, 63, 69, 21, 16, 23])

In [7]:
ary = np.array(np.random.randn(10)) # 표준정규분포를 따른 난수 생성 -> 초기 가중치 생성 때 사용
ary

array([ 0.62487856, -0.23692699,  0.14294364,  0.39334672, -0.26825795,
        0.70173382, -1.04482197, -0.55588542, -0.56443766,  1.07743663])

In [9]:
# 편향값 생성
bias = np.random.rand(1)
bias

array([0.26949719])

통계함수
- max, min, mean, median, var, std

In [10]:
np.max(ary)

98

Random 모듈
- seed : 랜덤 모듈의 규칙값
- randint: 랜덤 정수(범위지정 가능)
- randn : 표준정규분포를 따르는 난수 생성
- shuffle : 데이터 섞기
- choice : 특정확률로 데이터 뽑기

#### seed

In [12]:
seed = 603  # 머신러닝,딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1  = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [13]:
r1,r2,r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

※ 머신러닝 예시
- scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [16]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

X = np.random.randint(1, 100, 10).reshape(-1,2) # 5행 2열 데이터 생성
df = pd.DataFrame(X)

df

0   1
0  26  43
1  97  45
2  88  91
3  20  17
4  64  99

In [20]:
# Max와 Min값을 빼서 거리를 구하고, Min 값을 기준으로 각 값들의 위치값을 다시 정렬한 후 Max-Min거리 값으로 나눠주어 정규화 시킴 (0~1 사이의 값을 가지게 됨)
# 예시 Max : 97, Min : 20, Max-Min = 77
# 26 -> 6이 되고, 6/77 = 0.0779

scaled_data = MinMaxScaler().fit_transform(df)  
scaled_data, type(scaled_data)

(array([[0.07792208, 0.31707317],
        [1.        , 0.34146341],
        [0.88311688, 0.90243902],
        [0.        , 0.        ],
        [0.57142857, 1.        ]]),
 numpy.ndarray)

※ 머신러닝 예시
- 초기값을 임의로 생성하여 zero 행렬을 생성하여 대입할 때 다음과 같은 행렬을 작성하시오
$$ 
    \begin{pmatrix}
    난수 & 0 & 0 & 0 \\
    0 & 난수 & 0 & 0 \\
    0 & 0 & 난수 & 0 \\
    0 & 0 & 0 & 난수
    \end{pmatrix}
$$

In [51]:
# 내가 짠 코드

zero_ary = np.zeros((4,4))
random_num = np.random.randn(4)
for i, n in enumerate(random_num):
    zero_ary[i][i] = n
    
zero_ary

array([[-0.59126964,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.52189332,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.24765071,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.55796122]])

In [52]:
# 보여주신 코드

w = np.random.randn(4)
shp = np.zeros((4,4))

for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j: shp[i][j] = w[i]
        
shp

array([[-0.52281148,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.41020619,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.24111762,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.80007587]])

diag 함수를 사용하여 한줄 코드로 만들어버리기

In [48]:
import numpy as np
diag_matrix = np.diag(np.random.rand(4))

diag_matrix

array([[0.94795561, 0.        , 0.        , 0.        ],
       [0.        , 0.68153037, 0.        , 0.        ],
       [0.        , 0.        , 0.96592503, 0.        ],
       [0.        , 0.        , 0.        , 0.55072509]])