In [241]:
# from sklearn import svm,metrics
from sklearn.neighbors import KNeighborsClassifier # 분류
from sklearn.neighbors import KNeighborsRegressor  # 회귀-예측
from sklearn.linear_model import LinearRegression  # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항 feature를 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib

# maplotlib.rcParams['font.family'] = 'AppleGothic Gothic   # Mac 사용자
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = '10'  # 글자크기
matplotlib.rcParams['axes.unicode_minus'] = False

In [242]:
df = pd.read_csv('https://bit.ly/fish_csv_data')
df.head(3)
len(df)

159

In [243]:
# 0. 데이터 확인 : : Nan, 0, 타입, 최소값, 최댓값, 분포, 각 특성별 데이터 최대값(x,y축 범위가 다를 때 표준화 시켜야함)
df.shape
# df[df.columns[1]].unique()  # 0값이 있는지 없는지 확인
# df.info()
# df.describe()

(159, 6)

In [244]:
# 1. 데이터 전처리 - train, test set 분리
data = df.iloc[:,1:].to_numpy()
target = df['Species'].to_numpy()

# train, test 세트 분리
train_input,test_input,train_target,test_target = train_test_split(
    data,target
)

In [245]:
# 1-2. 표준화 작업
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)   # 데이터 훈련
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [246]:
# 2. 데이터 실습시키기
# 로지스틱 회귀모델로 데이터 훈련
from sklearn.linear_model import LogisticRegression
# max_iter : 반복횟수 = 100 기본설정
# C 규제 : 값이 작을수록 규제 강함
# 선형회귀 규제 - alpha값으로 지정(클수록 규제 강함)

lr = LogisticRegression(C=30, max_iter=1000)
lr.fit(train_scaled, train_target)

LogisticRegression(C=30, max_iter=1000)

In [247]:
# 3. 데이터 예측
predict = lr.predict(test_scaled[:5])
print(predict)

['Roach' 'Bream' 'Pike' 'Roach' 'Pike']


In [248]:
# 4. 데이터 정답률(정확도) - train, test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

# 과소적합 뜸 
# 로지스틱 회귀 반복횟수 늘리기, 규제 조정

0.9327731092436975
0.9


In [249]:
print(lr.classes_) # : proba 결과값 참고용 속성 값 순서

predict = lr.predict(test_scaled[:5])
print(predict)

proba = lr.predict_proba(train_scaled[:5])
print(np.round(proba,decimals=3))


# 기울기 y절현의 값을 적용시켜서 z  점수 출력
# softmax 함수를 적용해서 가증 높은 확률을 채택해서 결정함

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
['Roach' 'Bream' 'Pike' 'Roach' 'Pike']
[[0.    0.002 0.861 0.006 0.107 0.    0.025]
 [0.    0.    0.008 0.992 0.    0.    0.   ]
 [0.    0.02  0.41  0.    0.536 0.    0.033]
 [0.    0.    0.001 0.    0.    0.998 0.   ]
 [0.    0.008 0.84  0.    0.137 0.01  0.005]]


In [250]:
print(lr.classes_)

decisions = lr.decision_function(test_scaled[:5])
print(np.round(decisions, decimals=2 ))

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
[[ -2.81   0.77   3.28  -1.68   4.38  -5.86   1.92]
 [  8.82   4.87  -3.02  -1.13   3.73 -17.73   4.44]
 [ -1.87  -6.61   7.2    9.22   2.38 -12.08   1.77]
 [ -0.35   0.95   3.28  -0.74   3.81  -9.69   2.73]
 [ -2.42  -9.39   7.81  13.52   1.74 -12.44   1.19]]


In [251]:
# 다중분류, classes에 따른 예측 확률
from scipy.special import softmax

proba = softmax(decisions, axis=1)
print(np.round(proba, decimals=3))

[[0.001 0.019 0.228 0.002 0.692 0.    0.059]
 [0.963 0.019 0.    0.    0.006 0.    0.012]
 [0.    0.    0.117 0.882 0.001 0.    0.001]
 [0.008 0.028 0.292 0.005 0.498 0.    0.168]
 [0.    0.    0.003 0.997 0.    0.    0.   ]]
